### ISSUE TITLE
Prevent silent errors

### ISSUE THREAD

**Issue by EHLOVader** [morrislaptop/laravel-elixir-useref#2]
I think this is a problem with usefref. I remember seeing it from my gulpfile before. But perhaps here in Elixir we have an option to capture it.

I wasn't getting any files and later found that the files I was referencing in the build blocks from my public directory weren't being found causing the whole stream to stop and preventing all useref files from being created.

Is it possible to add error handling or notifications if an asset file isn't found or valid by useref?

**Comment by morrislaptop** [comment]
Mmmm yeah I'm not going to touch that one and leave it up to the (gulp-)useref guys..

Unfortunately I don't really a see of way of doing this outside the plugin as elixir doesn't expose the stream :(
