### ISSUE TITLE
Broken in Elixir 2.0

### ISSUE THREAD

**Issue by EHLOVader** [morrislaptop/laravel-elixir-useref#6]
This is now broken in elixir 2.0 because it wasn't properly pinned to a version.

Admittedly Laravel didn't do a good job of documenting the switch, but can you fix your package with a 2.x branch with the current major version, and the old code that worked for Elixir 2.x and bump the major version of your master when you return the code to the current one?

You can see how I did it here https://github.com/EHLOVader/laravel-elixir-livereload/

I also used peerDependencies to prevent installation in the case the wrong version of Elixir was installed for the current version of my package.

**Comment by EHLOVader** [comment]
Looking at the history I have no clue how this hasn't been a problem for me in the past. 

It says you merged the update for Elixir 3.0 many days ago, but it has only just stopped working in my deployment process. Which is a critical problem for me.

**Comment by morrislaptop** [comment]
Hi Joseph,

Ah I just pushed it up to the NPM repo the other day. I would suggest
putting the explicit version number in your package.json so you don't get
the updated version.

Cheers,
Craig

**Comment by morrislaptop** [comment]
Also happy for a PR for the peerDependencies, I don't think that was fully established yet when I pushed this library :)

**Comment by EHLOVader** [comment]
Ah! thanks @morrislaptop it was the npm publish that was done that broke it, I was only looking at the pushes to github (I assumed that if it was pushed it would also have been published)

I can look into writing up a PR. not sure what was fully established? [peerDependencies have been around a long while it seems](http://blog.nodejs.org/2013/02/07/peer-dependencies/) But no fault of yours. The documentation and api change done by Laravel-Elixir was poorly documented and didn't take into account the many plugins that were out there, that the might not all upgrade at once, and that some of their users might not want to upgrade yet.

Adding the explicit version myself. If however you have to support upgrades or api changes in useref for Elixir 2x users you will not have the room to do so. You didn't bump a major version so it might be tricky.
